name: Main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Update dates.txt with new date
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git checkout master
        touch dates.txt
        echo `date` >> dates.txt
        cat dates.txt
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git add dates.txt
        git commit -m "github-actions: update dates.txt"
        GIT_TRACE=1 git push --verbose
